version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5434:5432'
    volumes:
      - C:\Users\Soma\data\postgres:\data\postgres
    env_file:
      - docker.env
